### ISSUE TITLE
source/lexer.d(649,10): Error: returning this.cur escapes a reference to parameter this, perhaps annotate with return

### ISSUE THREAD

**Issue by timotheecour** [burner/graphqld#1]
dub build
Fetching stdx-allocator 2.77.1 (getting selected version)...
Fetching fixedsizearray 1.1.1 (getting selected version)...
Fetching exceptionhandling 0.1.0 (getting selected version)...
Fetching vibe-d 0.8.3 (getting selected version)...
Fetching taggedalgebraic 0.10.11 (getting selected version)...
Performing "debug" build using dmd for x86_64.
graphqld ~master: building configuration "library"...
source/lexer.d(649,10): Error: returning this.cur escapes a reference to parameter this, perhaps annotate with return
source/parser.d(51,34): Error: constructor vibe.utils.array.AllocAppender!(string, immutable(char)).AllocAppender.this(IAllocator alloc, char[] initial_buffer = null) is not callable using argument types (IAllocator)
source/parser.d(51,34):        cannot pass argument this.alloc of type std.experimental.allocator.IAllocator to parameter IAllocator alloc
source/parser.d(92,34): Error: constructor vibe.utils.array.AllocAppender!(string, immutable(char)).AllocAppender.this(IAllocator alloc, char[] initial_buffer = null) is not callable using argument types (IAllocator)

**Comment by burner** [comment]
could you please try master
