### ISSUE TITLE
aggregate whose single field selected is null is listed as null for the aggregate

### ISSUE THREAD

**Issue by schveiguy** [burner/graphqld#22]
For example, say you have a query like this:

```
{
  endpoint {
    info {
      id
      possiblyNull
    }
  }
}
```

And you get back this result:

```json
{
  "error": [],
  "data": {
    "endpoint": [
      {
        "info": {
          "possiblyNull": "foobar",
          "id": 1
        }
      },
      {
        "info": {
          "possiblyNull": null,
          "id": 2
        }
      }
    ]
  }
}
```

If you remove `id` from the selection, you instead get:

```json
{
  "error": [],
  "data": {
    "endpoint": [
      {
        "info": {
          "possiblyNull": "foobar"
        }
      },
      {
        "info": null
      }
    ]
  }
}
```

Where I would expect to see the full object of `info` on the second record, just with the `possiblyNull` field set to `null`.

**Comment by burner** [comment]
as it turns out it actually has to be this way (as currently implemented).
The execution of a SelectionSet has to stop if the parent is null. That includes containing keys with null values as well.

take this fragment for example.
No matter the type it will try to recursive, when if there is no more ofType.

```graphql
fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by schveiguy** [comment]
But the issue is not that the parent is null. It’s that the child is null. I’d expect a non null parent with a single null child.

**Comment by burner** [comment]
I'm not 100% if this is what you mean.

If you run:
```graphql
{
	starships(overSize: 600) {
		commander {
			allwaysNull {
				id
			}
		}
	}
}
```
I think you want to get back this:
```graphql
{
	"starships" : [
		{
			"commander" : {
				"allwaysNull": null
			}
		}
	]
}
```
If I run that, I get the expected output.
Thoughts?

**Comment by schveiguy** [comment]
Nope, it's more like this:

```graphql
 {
 	starships(overSize: 600) {
 		commander {
 			possiblyNullLeaf
 		}
 	}
 }
 ```
And I would expect to get back  what you posted as the result (replace `alwaysNull` with `possiblyNullLeaf`), but instead I get this:

```graphql
{
	"starships" : [
		{
			"commander" : null
		}
	]
}
```

Suggesting that there is no commander. I want to see that there is a commander but that maybe the subfield is null instead of that the whole thing is null.

**Comment by burner** [comment]
ok
```graphql
{
	starships(overSize: 600) {
		commander {
			alsoAllwaysNull
		}
	}
}
```
gives me
```graphql
{
	"starships" : [
		{
			"commander" : {
				"alsoAllwaysNull": null
			}
		}
	]
}
```

**Comment by schveiguy** [comment]
This was not my experience. But `alsoAlwaysNull` is an aggregate, right? What if it's just a leaf node?

**Comment by burner** [comment]
alsoAlwaysNull is an Nullable!int

**Comment by schveiguy** [comment]
OK, so that is different than my experience. I don't have time right now. Maybe on the flight, I will be able to figure out to reproduce.

**Comment by burner** [comment]
sounds, good.
Hopefully, I fixed it accidentally ;-)

**Comment by schveiguy** [comment]
OK, so here's an example from our codebase:

```graphql
{allEmployees
{
  info
  {
    id
    addressInstance
    {
      line1
      line2
    }
  }
}}
```

I get, as part of my query result (trimmed to show the issue):

```json
      {
        "info": {
          "addressInstance": {
            "line1": "Paris Corners",
            "line2": "Apt. 831"
          },
          "id": 2
        }
      },
      {
        "info": {
          "addressInstance": {
            "line1": "Wolff Brooks",
            "line2": null
          },
          "id": 5
        }
      },
```

Note that id 5 has a null line2 in the address instance. If I remove the line1 request:

```graphql
{allEmployees
{
  info
  {
    id
    addressInstance
    {
      line2
    }
  }
}}
```

It now claims that the addressInstance itself is null:

```json
      {
        "info": {
          "addressInstance": {
            "line2": "Apt. 831"
          },
          "id": 2
        }
      },
      {
        "info": {
          "addressInstance": null,
          "id": 5
        }
      },
```

What I would expect to see is this:

```json
      {
        "info": {
          "addressInstance": {
            "line2": "Apt. 831"
          },
          "id": 2
        }
      },
      {
        "info": {
          "addressInstance": {
            "line2": null
          },
          "id": 5
        }
      },
```

**Comment by moon-chilled** [comment]
A similar issue I've encountered recently: empty arrays turn into null.
