### ISSUE TITLE
How to use unions?

### ISSUE THREAD

**Issue by schveiguy** [burner/graphqld#38]
I tried to use a union in our project to return a union of Long, String, or Bool.

essentially I have a schema function that looks like this:

```D
struct LongValue {
long value;
}

struct StringValue {
string value;
}

struct BoolValue {
bool value;
}
union Value {
   LongValue longVal;
   StringValue strVal;
   BoolValue boolVal;
}

struct SomeItem {
   Value valByName(string name);
}
```

I did objects instead of straight scalars because GraphQL only allows objects as union members.

But when I register a handler for valByName, I get the error message `No return type for member 'valByName' of type 'SomeItem' found`. What am I doing wrong? I didn't see any example of using unions in any of the test code. There is a union in the test schema, but there's no usage of it.

**Comment by schveiguy** [comment]
I am working on this some more, gave up on the union for now, and I still get the "no return type for..." error. So maybe that has nothing to do with unions.

BUT... there still should be an example of how to do unions for the library.

**Comment by burner** [comment]
yeah, my holiday is ending. I'm back in the office on monday. I'll have a look then.

**Comment by burner** [comment]
I added an example how to use a union here
https://github.com/burner/graphqld/blob/master/test/source/app.d#L53

unions have to be structs because they need a __typename member to use fragments.
So that is by design.
