### ISSUE TITLE
methods on types should be exposed as fields

### ISSUE THREAD

**Issue by schveiguy** [burner/graphqld#40]
If I create a schema with types that have members that are functions, they are exposed as fields, but don't work.

for example:

```D
struct SomeType
{
    int foo();
}
struct Query
{
   SomeType someType();
}
class Schema
{
   Query queryType;
}
```

If my query for example has:
```graphql
{
   someType {
      foo
   }
}
```

I would expect to get JSON back reflecting foo equal to some integer. But I get the message "No return type for member 'foo' of type 'SubType' found"

When I look at the graphql code, it's hard to tell where the fields are registered. I can query the schema and everything looks great, I see `foo` as a field of `SubType`, I see it's type is NON-NULL of type Int. I see it takes no args. But it just doesn't work. I've registered a handler for it.

What I think is happening is that all types EXCEPT the main 3 (`queryType`, `mutationType`, `subscriptionType`) are registered via typeToGQLDType (graphqld.schema.types). This only registers *fields* of an aggregate, not members. The main 3 are registered via `toSchema` (graphqld.schema.resolver), which ironically only processes callables (i.e. you cannot just stick a subType in there as a member).

I think both cases should handle callables and fields. I'll see if I can make a PR to do this, and see what happens.

**Comment by schveiguy** [comment]
I created a branch which does what I thought it might. But... it kinda sucks. I'm creating a PR that you should NOT pull. But we can talk about it there. PR is #41

**Comment by burner** [comment]
try adding @GQLDUda(TypeKind.OBJECT) to your query struct like in
https://github.com/burner/graphqld/blob/master/source/graphql/testschema.d#L34

**Comment by schveiguy** [comment]
That does not change anything.

Here is my full code: https://gist.github.com/schveiguy/47d01f36e8eb41512529c68843ebbf77

**Comment by burner** [comment]
something is off, is copy pasted, called dub, and it just worked

**Comment by schveiguy** [comment]
It builds and runs. But does it work? Can you use a graphql query to get foo or foo2?

**Comment by burner** [comment]
I see

**Comment by burner** [comment]
I took your PR #41 and made a tiny improvement. Thank you. Feel like the reflection needs a rewrite at some point.

**Comment by burner** [comment]
please reopen if v2.0.2 does not fix this

**Comment by schveiguy** [comment]
Thanks, it works for me on the test case. Probably needs some test cases for it. I'll take a look later at our project to see if it helps for what I'm trying to do.
