### ISSUE TITLE
Using graphqld with vibe.mongo leads to clock_gettime error

### ISSUE THREAD

**Issue by serates** [burner/graphqld#48]
Hello I am trying to now use graphqld with vibe.d's mongo integration and noticed a problem with class/structs that use the BsonObjectID type. 

For example using a object type like:
`struct Item { BsonObjectID id; }`

will result in

`/usr/include/dmd/phobos/std/datetime/systime.d(253,52): Error: clock_gettime cannot be interpreted at compile time, because it has no available source code`

Now i've tried working around this by using GQLDCustomLeaf but instead this ends up leading to vibe mongo no longer storing the id as a proper ObjectID. Do you know of a recommended way of handling BsonObjectID that graphqld and vibe.d are both happy with?

**Comment by burner** [comment]
What is BsonObjectID actually? 

have a look at my GQLDCustonLeaf for std.DateTime here

https://github.com/burner/graphqld/blob/master/source/graphql/testschema.d#L63

https://github.com/burner/graphqld/blob/master/source/graphql/testschema.d#L30

https://github.com/burner/graphqld/blob/master/source/graphql/testschema.d#L34

you have to implement the from/to conversion and then use the GQLDCustomLeaf around.

please reopen if this doesn't work.

**Comment by serates** [comment]
So by default this doesn't work because when vibe.db.mongo serialized the object it creates a weird nested object instead of the BsonObjectID. However i found a fix that is rather interesting. By adding the following to the definition of GQLDCustomLeaf:

`
        static GQLDCustomLeaf!(T, SerializationFun, DeserializationFun) fromRepresentation(T input) @safe {
		return GQLDCustomLeaf!(T, SerializationFun, DeserializationFun)(input);
	}

	T toRepresentation() @safe {
		return this.value;
	}
`

This allows the vibe serializer to serialize the custom leaf object like it was T which fixes the use for me

**Comment by burner** [comment]
cool, I guess this closes this issue. I like it when people fix stuff for me. Keep the issus/fixes coming. Thanks Robert
