### ISSUE TITLE
Code clarification

### ISSUE THREAD

**Issue by aberba** [burner/graphqld#56]
What's happening in this piece of code?

```d
Document d = p.parseDocument();
const(Document) cd = d;
auto fv = new QueryValidator(d);
fv.accept(cd);

noCylces(fv.fragmentChildren);
allFragmentsReached(fv);

...
sv.accept(cd);
```

**Comment by burner** [comment]
@aberba have a look and please reopen if you think more doc is required

**Comment by aberba** [comment]
@burner thanks. It's now very clear to me how it works. I'm planning to write a tutorial on it so I wanted to be certain about my understanding. 

Thanks again.
